# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
  pull_request:
    paths:
      - prog_models

jobs:
  analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        python -m pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 src/prog_models --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 src/prog_models --count --benchmark --exit-zero --show-source --max-complexity=10 --max-line-length=127 --statistics --tee --output-file=lint_results_${{ matrix.python-version }}.txt
    - name: Upload Lint Results
      uses: actions/upload-artifact@v2
      with: 
        name: lint_results_${{matrix.python-version}}
        path: lint_results_${{matrix.python-version}}.txt
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'python' 
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
    - name: Run tests
      run: python -m tests
  test_prog_algs_released:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
    - name: Clone prog_algs
      uses: actions/checkout@v2
      with:
        repository: nasa/prog_algs 
        ref: refs/heads/master
        path: prog_algs
    - name: Install prog_algs
      run: | 
        python -m pip install -e ./prog_algs
    - name: Run tests
      run: |
        cd prog_algs 
        python -m tests
  test_prog_algs_dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
    - name: Clone prog_algs
      uses: actions/checkout@v2
      with:
        repository: nasa/prog_algs 
        ref: refs/heads/dev
        path: prog_algs
    - name: Install prog_algs
      run: | 
        python -m pip install -e ./prog_algs
    - name: Run tests
      run: |
        cd prog_algs 
        python -m tests
